# Generated by Django 4.2.3 on 2023-07-09 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('maintenance', 'Maintenance')], default='idle', max_length=20)),
                ('current_floor', models.IntegerField(default=1)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stopped', 'Stopped')], default='stopped', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elevator.elevator')),
            ],
        ),
    ]
